plugin_dir: ~/.config/nvim/pack/strand/start

plugins:
  - Git: arzg/vim-colors-xcode
  - Git: arzg/vim-rust-syntax-ext
  - Git: junegunn/fzf.vim
  - Git: junegunn/vim-easy-align
  - Git: lifepillar/vim-colortemplate
  - Git: romainl/vim-cool
  - Git: rust-lang/rust.vim
  - Git: tpope/vim-endwise
  - Git: tpope/vim-fugitive
  - Git: tpope/vim-surround
  - Git: wellle/targets.vim
